name: stepel
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.7.0
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  sleek_circular_slider: ^2.0.1
  flutter_svg: ^2.0.7
  fl_chart: ^0.63.0
  pedometer: ^4.0.1
  flutter_bloc: ^8.1.3
  geolocator: ^9.0.2
  flutter_background_service: ^3.0.1
  flutter_local_notifications: ^15.1.0+1
  equatable: ^2.0.5
  permission_handler: ^10.4.2
  sensors: ^2.0.3
  drift: ^2.10.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  intl: ^0.18.1
  meta: ^1.9.1
  numberpicker: ^2.1.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.2.0
  drift_dev: ^2.10.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/icons/

